export const AppErrorStatusCode = {
  // server
  INTERNAL_SERVER_ERROR: 5000,
  TIMEOUT: 5031,
  VALIDATION: 4000,

  // auth
  AUTH: {
    JWT_ACCESS_TOKEN: 5100,
    JWT_REFRESH_TOKEN: 5101
  },

  // policy
  POLICY: {
    ABILITY_FORBIDDEN: 5050,
    ROLE_FORBIDDEN: 5051,
    ABILITY_PREDEFINED_NOT_FOUND: 5052,
    ROLE_PREDEFINED_NOT_FOUND: 5053
  }
};
